// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC-CCBuqlA_nGEI3-bpTZLzaiBwCxOQzk',
    appId: '1:337669326034:web:e336c866dd6cfdc793d90b',
    messagingSenderId: '337669326034',
    projectId: 'learning-minimal-social-media',
    authDomain: 'learning-minimal-social-media.firebaseapp.com',
    storageBucket: 'learning-minimal-social-media.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3XABpuVSVY4v-cuVmlv2RtQpWqPRBV8M',
    appId: '1:337669326034:android:5f8357e9ea9ff73f93d90b',
    messagingSenderId: '337669326034',
    projectId: 'learning-minimal-social-media',
    storageBucket: 'learning-minimal-social-media.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV5zwXQRbwz_ZPZW9auU3cgpWTQ24tdSo',
    appId: '1:337669326034:ios:21c9cb692eb5c37993d90b',
    messagingSenderId: '337669326034',
    projectId: 'learning-minimal-social-media',
    storageBucket: 'learning-minimal-social-media.appspot.com',
    iosBundleId: 'com.example.learningMinimalSocialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV5zwXQRbwz_ZPZW9auU3cgpWTQ24tdSo',
    appId: '1:337669326034:ios:21c9cb692eb5c37993d90b',
    messagingSenderId: '337669326034',
    projectId: 'learning-minimal-social-media',
    storageBucket: 'learning-minimal-social-media.appspot.com',
    iosBundleId: 'com.example.learningMinimalSocialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAC-CCBuqlA_nGEI3-bpTZLzaiBwCxOQzk',
    appId: '1:337669326034:web:1c7e5335d1fc502593d90b',
    messagingSenderId: '337669326034',
    projectId: 'learning-minimal-social-media',
    authDomain: 'learning-minimal-social-media.firebaseapp.com',
    storageBucket: 'learning-minimal-social-media.appspot.com',
  );

}